### ISSUE TITLE
How do I get the access token from a code I already have?

### ISSUE THREAD

**Issue by cinjon** [googleapis/google-auth-library-python-oauthlib#64]
I used ReactGoogleLogin (https://github.com/anthonyjgrove/react-google-login) to get the offline `code`. This works fine and is associated with my clientId. I then want to have the server complete the process with this API.

Doing the following does not work and yields an error `oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) code_verifier or verifier is not needed.`. How do I fix this?

```
def fetch_token(code):
  flow = Flow.from_client_secrets_file(</path/to/credentials.json>, [list of scopes], 
    redirect_uri='urn:ietf:wg:oauth:2.0:oob')
  flow.fetch_token(code)
```

Note that I tried this w/ and w/o the redirect_uri. I also tried it with the redirect_uri for my website. All gave the same error.

**Comment by cinjon** [comment]
I changed this to use a site-specific redirect uri and now I'm getting:

`oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (redirect_uri_mismatch) Bad Request`

This seems pretty common but none of the solutions I see are working for me.

**Comment by busunkim96** [comment]
Hiya @cinjon 

I think you're running into a bug introduced in v0.4.0. Please use 0.3.0 until the fix is released in 0.4.1

**Comment by cinjon** [comment]
I tried downgrading and am still getting the same error:

`oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (redirect_uri_mismatch) Bad Request`

**Comment by cinjon** [comment]
Is there a way to get more visibility into what is the error? All I'm seeing is `oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (redirect_uri_mismatch) Bad Request` but the redirect_uri is the same on both the client and the server.

**Comment by busunkim96** [comment]
Hmm, can verify that the desired redirect_uri is in the `credentials.json` file?  It should be listed under the `redirect_uris` field.

**Comment by cinjon** [comment]
So that was an issue, and I've now updated it - and I still get the same error. Fwiw, this is all happening in local development. 

My current credentials.json looks like:
`{"web":{"client_id":"<blah>.apps.googleusercontent.com","project_id":"<blah>","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"<blah>","redirect_uris":["https://localhost:3000/google_oauth_redirect","http://localhost:3000/google_oauth_redirect","http://localhost:5000/google_oauth_redirect","https://localhost:5000/google_oauth_redirect"],"javascript_origins":["https://localhost:3000","http://localhost:3000","https://localhost:5000","http://localhost:5000"]}}
`

As you can see, I have inserted all the things I could think of to try and get it to not be a mismatch. I've also tried the redirect_uri combinations in my local JS as well. 

Do you have more suggestions? That last one was really useful. Thanks!

**Comment by busunkim96** [comment]
@cinjon Did you edit the file manually? If so, you should go to the [API console](http://console.cloud.google.com/apis/credentials/) and edit your existing OAuth client ID. After that you can re-download the credentials.

**Comment by cinjon** [comment]
I didn't. I downloaded it from the console.

**Comment by busunkim96** [comment]
It looks like the library you linked is using gapi under the hood. You might want to take a look at that documentation as well.

https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig
![image](https://user-images.githubusercontent.com/8822365/66235504-02a6f800-e6a5-11e9-8c18-6acce17ce161.png)

There are some more general suggestions in [this stackoverflow post](https://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch).

**Comment by busunkim96** [comment]
When you do figure out the solution, would you mind posting back here? It will help who stumbles on this issue in the future. :smiley:

**Comment by Andras1000** [comment]
This happened to me after trying to use the OAuth2 authorization code more than once.

**Comment by jahangirkabir** [comment]
I am also getting the same error with version 0.4.2

**Comment by busunkim96** [comment]
Revisiting this, I think @Andras1000 is correct.

To get a new access token you need to use the **refresh token**.
![image](https://user-images.githubusercontent.com/8822365/100251394-f3fc4f80-2efb-11eb-82dd-e77c1de99a30.png)

Documentation:
* https://developers.google.com/identity/protocols/oauth2
* https://developers.google.com/identity/protocols/oauth2/web-server#offline

**Comment by Chokerino** [comment]
@busunkim96 How do i get the refresh token tho? I have got the authorization code from the front end and want to store the refresh token in my django backend.

**Comment by busunkim96** [comment]
@Chokerino The authorization code should be exchanged for a refresh token. https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code
